### PR TITLE
Added abc.txt with the following features

### PR DESCRIPTION
**Pull request by nasirhm**
Hey Doug, I've added the abc.txt file, Kindly review

### CODE REVIEW

**Comment by nerd-code** [comment]
Hey Dana,  please add the last line of abc.txt file.

**Comment by nasirhm** [comment]
> Hey Dana, please add the last line of abc.txt file.

Hey Doug, here's the fix: https://github.com/nerd-code/learning-git/pull/1/commits/c0822b025582a6f0a7f83ed1d5457886035c2c73

When i pushed the code to the branch which i made PR from, it automatically added the last commit in this PR.

**Comment by nasirhm** [comment]
As you can think of it as, If i'm working on 2 features simultaneously and create two different branches. So, if someone reviews my code and recommend fixes i can do these with ease for both :)

**Comment by nerd-code** [comment]
Okay Dana, let's merge your edits.

**Comment by nasirhm** [comment]
Thanks Doug. :)

**Pull request merged**
